### ISSUE TITLE
安装完主程序报错，读取主题配置文件失败,直接启动不了

### ISSUE THREAD

**Issue by asd123wto** [ruibaby/casper-halo#14]
halo v1.4.1
主题是远程安装
安装完不能启动，提示“读取主题配置文件失败”
重启程序就先报错再自动关闭，只能把文件都删了才重新启动安装
这也太bug了吧，难道是我安装的姿势不对？

**Comment by ruibaby** [comment]
没有成功复现，发行版和开发版都能成功下载。请给出异常日志，抱怨一番无法解决任何问题。
