### ISSUE TITLE
casper主题的图片是如何自动生成的？？

### ISSUE THREAD

**Issue by ghost** [ruibaby/casper-halo#3]

**Comment by ruibaby** [comment]
哪个地方？文章列表吗？

**Comment by ghost** [comment]
您好！就是在发布文章的时候的配图，这个是怎么自动生成的呢？？
----- 原始邮件 -----
发件人：Ryan Wang <notifications@github.com>
收件人：halo-dev/halo-theme-casper <halo-theme-casper@noreply.github.com>
抄送人：HCJ-shadow <glaring1shadow@sina.com>,  Author <author@noreply.github.com>
主题：Re:_[halo-dev/halo-theme-casper]_casper主题的图片是如何自动生成的？？_(#3)
日期：2019年06月16日 14点27分

哪个地方？文章列表吗？



&mdash;

**Comment by ruibaby** [comment]
没有自动生成，发布文章的时候可以设置。
